#!/usr/bin/env bash

set -euf -o noclobber -o noglob -o nounset
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}" # protect trailing \n

PATH=$PATH:"${XDG_CONFIG_HOME:-$HOME/.config}/nnn/plugins"

FPATH="$1"
FNAME=$(basename "$1")
EDITOR="nano"
PAGER="${PAGER:-less -R}"
ext="${FNAME##*.}"
if [ -n "$ext" ]; then
    ext="$(printf "%s" "${ext}" | tr '[:upper:]' '[:lower:]')"
fi

handle_pdf() {
    if type zathura  >/dev/null 2>&1; then
            zathura "${FPATH}" >/dev/null 2>&1 &
 fi
    exit 0
}

handle_av() {
    if type mpv  >/dev/null 2>&1; then
        mpv --player-operation-mode=pseudo-gui  "${FPATH}" >/dev/null 2>&1 &
    fi
    exit 0
}

# handle this extension and exit
handle_extension() {
    case "${ext}" in
        ## PDF
        pdf|epub)
            handle_pdf
            exit 1;;

        ## Audio
        aac|flac|m4a|mid|midi|mpa|mp2|mp3|ogg|wav|wma)
            handle_av
            exit 1;;

        ## Video
        avi|mkv|mp4|ts)
            handle_av
            exit 1;;
 ## Archive
        a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|\
        rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)
            if type 7zz >/dev/null 2>&1; then
                7zz l -p -- "${FPATH}" | eval "$PAGER"
                exit 0
            fi
            exit 1;;
        rar)
            if type unrar >/dev/null 2>&1; then
                ## Avoid password prompt by providing empty password
                unrar lt -p- -- "${FPATH}" | eval "$PAGER"
            fi
            exit 1;;
    esac
}

handle_mime() {
    mimetype="${1}"
    case "${mimetype}" in

        ## Image
        image/*)
                if type mvi >/dev/null 2>&1; then
                      mvi  "${FPATH}" >/dev/null 2>&1 &
                    exit 0
                fi
            exit 7;;

        ## PDF
        application/pdf)
            handle_pdf
            exit 1;;

        ## Audio
        audio/*)
            handle_audio
            exit 1;;

        ## Video
        video/*)
            handle_video
            exit 1;;

        ## Text
        text/* | */xml)
            "$EDITOR" "${FPATH}"
            exit 0;;

    esac
}

handle_fallback() {
        if type xdg-open >/dev/null 2>&1; then
            nohup xdg-open "${FPATH}" >/dev/null 2>&1 &
            exit 0
        fi
    echo '----- File details -----' && file --dereference --brief -- "${FPATH}"
    exit 1
}



MIMETYPE="$(file -bL --mime-type -- "${FPATH}")"
handle_extension
handle_mime "${MIMETYPE}"
handle_fallback

exit 1
