#!/bin/sh
case "$(printf "Apps\\nMedia\\nLibrary\\nWin"|wofi --dmenu -l 6 -i -p "Mount Ntfs:")" in
Apps)   doas ntfs-3g /dev/sda1 ~/mnt/aps ;;
Media) doas ntfs-3g /dev/sda3 ~/mnt/med;;
Library) doas ntfs-3g /dev/sda5 ~/mnt/lib;;
Win)  doas ntfs-3g /dev/sda4 ~/mnt/win;;
esac
